### ISSUE TITLE
Add size token with a value of `0`

### ISSUE THREAD

**Issue by jordanjones243** [AlaskaAirlines/AuroDesignTokens#143]
### General Support Request

We need to add a design token with a value of `0` in order to make Auro components fully customizable.

### Possible Solution

Add `--ds-size-none` token

### Additional context

We previously had an `--auro-size-none` token, but it has been recently deprecated and there was no token to replace it.

**Comment by blackfalcon** [comment]
I don't think having a token for `--ds-size-none` or `--ds-size-0` is necessary since this value will likely never change. Updating `--ds-size-none` to something like `1rem` when changing a theme just doesn't seem practical. It's akin to changing `--ds-color-brand-atlas-400` to `#FFA500`.

This kind of token should probably be categorized as tier 2 or even tier 3. For instance, with [auro-input](https://github.com/AlaskaAirlines/auro-input/blob/2ca091fff3015b7d7205e39e41e00a53844b4213/src/styles/input.scss#L17), `input-margin` could be such a token, set to `0` by default, but modifiable in a theme.

This also brings up the broader issue of how users can customize the values of tier 3 tokens. After some research, it seems the only way to do that is by injecting new code into the web component's scope. Here's a demo of how it could be done:

```js
const myInput = document.querySelector('auro-input');
const shadowRoot = myInput.shadowRoot;

// Create a new CSSStyleSheet
const customStyles = new CSSStyleSheet();
customStyles.replaceSync(`
  input {
    input-margin: 1rem;
  }
`);

// Apply the custom styles to the shadow DOM
shadowRoot.adoptedStyleSheets = [customStyles];
```

**Comment by Patrick-Daly-AA** [comment]
Move above comment to a discussion, then we can close this issue.
