### ISSUE TITLE
Use design tokens from this project in Figma files

### ISSUE THREAD

**Issue by blackfalcon** [AlaskaAirlines/AuroDesignTokens#68]
## Is your feature request related to a problem? Please describe

Having a standard integration model for our design token solution and Figma would really help to maintain consistency and a single source of truth.

## Describe the solution you'd like

Please look at this plugin and evaluate its use. 

https://www.figma.com/community/plugin/843461159747178978/Figma-Tokens

## Describe alternatives you've considered

If this plug in will assist in maintaining a format from which we can import tokens from our solution, then that would really help to maintain consistency. 

## Additional context

Inspirations 

https://github.com/divriots/style-dictionary-to-figma
https://twitter.com/WestbrookJ/status/1501831912423575554?s=20&t=5tWCzMdN4Hhd0wcdz_gQLA

**Comment by leeejune** [comment]
This is an AMAZING plugin. I absolutely love it. I have a few concerns though:
1. There is no "internal" storage that designers can use within Figma. In other words, designers need to learn how to use Github or understand how JSON works for them to use it correctly. This will lead to other problems (Github licensing, training, etc)
2. We have a large group of designers. This tool would be great for a small team to use, but we have a large number of contract & full time designers that are scattered across e-commerce. Every time something needs updating, designers will need to "pull" from the repo. If a designer wants to propose a new change (addition of spacing token, for example) they will need to learn how to make commits on Github. I can easily do this for them, but it seems like this will be another system to maintain... which leads me to my 3rd concern.
3. It is a completely different system to maintain apart from the Figma library. I think I'll need to weigh more options to implement this into our current system because the increase in efficiency should outweigh the extra maintenance/efforts it takes to facilitate an entirely new system.

I love, love, love this plugin... but I'm not sure if its the best for our current state.

**Comment by blackfalcon** [comment]
Fair. No need to push for this if it's not the right tool or time. We can close this and always come back to this later if needed.
